export const GET_IMAGES_LOADING = 'GET_IMAGES_LOADING';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_ERROR = 'GET_IMAGES_ERROR';

export const GET_CAROUSEL_IMAGES_LOADING = 'GET_CAROUSEL_IMAGES_LOADING';
export const GET_CAROUSEL_IMAGES_SUCCESS = 'GET_CAROUSEL_IMAGES_SUCCESS';
export const GET_CAROUSEL_IMAGES_ERROR = 'GET_CAROUSEL_IMAGES_ERROR';
